--SCRIPT DO BANCO DE DADOS PRODUCAO

--TABELA PRODUTOS

CREATE TABLE Produtos (
 	 CODIGO INTEGER NOT NULL,
     NOME VARCHAR(100) NOT NULL,
     QTD FLOAT NOT NULL,
     PRECO_CUSTO FLOAT NOT NULL,
     PRECO_VENDA FLOAT NOT NULL,
     TIPO_PRODUTO INTEGER NOT NULL
);

--PK 
ALTER TABLE Produtos ADD CONSTRAINT Produto_PK PRIMARY KEY (CODIGO);

--TABELA TIPO DE PRODUTOS

CREATE TABLE Tipo_Produto (
	CODIGO INTEGER NOT NULL,
	DESCRICAO VARCHAR(20) NOT NULL
);
--PK
ALTER TABLE Tipo_Produto ADD CONSTRAINT Tipo_PK PRIMARY KEY (CODIGO);

--FK (TABELA PRODUTOS)
ALTER TABLE Produtos ADD CONSTRAINT PRODUTOS_TIPO_FK
FOREIGN KEY (TIPO_PRODUTO) REFERENCES TIPO_PRODUTO(CODIGO);

-- INSERT TABELA TIPO DE PRODUTOS (VALORES PADRÃO)

INSERT INTO Tipo_Produto (CODIGO, DESCRICAO)
VALUES (1, 'Composição');

INSERT INTO Tipo_Produto (CODIGO, DESCRICAO)
VALUES (2, 'Componente');

--TABELA COMPOSICAO

CREATE TABLE Composicao(
	CODIGO_COMPOSICAO INTEGER NOT NULL,
	CODIGO_PRODUTO INTEGER NOT NULL,
	CODIGO_COMPONENTE INTEGER NOT NULL,
	QTD_COMPONENTE FLOAT NOT NULL
);

--PK

ALTER TABLE COMPOSICAO ADD CONSTRAINT CODIGO_COMPOSICAO_PK PRIMARY KEY(CODIGO_COMPOSICAO);

--FK

ALTER TABLE COMPOSICAO ADD CONSTRAINT CODIGO_PRODUTO_FK
FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTOS(CODIGO);

-- TABELA ORDEM PRODUCAO

CREATE TABLE ORDEMPRODUCAO(
	NUMERO INTEGER NOT NULL,
	DESCRICAO VARCHAR(60) NOT NULL,
	DATA_EMISSAO DATE NOT NULL,
	DATA_FINALIZACAO DATE NOT NULL,
	STATUS BOOLEAN NOT NULL
);

--PK

ALTER TABLE ORDEMPRODUCAO ADD CONSTRAINT NUMERO_PK PRIMARY KEY (NUMERO);

-- TABELA ITEM PRODUCAO
CREATE TABLE ITENSORDEMPRODUCAO(
	ID INTEGER NOT NULL,
	NUMERO_ORDEM INTEGER NOT NULL,
	CODIGO_ITEM INTEGER NOT NULL,
	QTD_PRODUZIDA FLOAT NOT NULL,
	CUSTO_UNITARIO FLOAT NOT NULL,
	CUSTO_TOTAL FLOAT NOT NULL
);

-- PK

ALTER TABLE ITENSORDEMPRODUCAO ADD CONSTRAINT ID_PK PRIMARY KEY(ID);

-- FK

ALTER TABLE ITENSORDEMPRODUCAO ADD CONSTRAINT NUMERO_ORDEM_FK
FOREIGN KEY (NUMERO_ORDEM) REFERENCES ORDEMPRODUCAO(NUMERO);

--FK

ALTER TABLE ITENSORDEMPRODUCAO ADD CONSTRAINT CODIGO_ITEM_FK
FOREIGN KEY (CODIGO_ITEM) REFERENCES PRODUTOS(CODIGO);

--INSERTS

INSERT INTO ORDEMPRODUCAO (NUMERO, DESCRICAO, DATA_EMISSAO, DATA_FINALIZACAO, STATUS)
VALUES (2, 'Producao 2', '25-11-2017', '25-11-2017', true);

INSERT INTO ITENSORDEMPRODUCAO(ID, NUMERO_ORDEM, CODIGO_ITEM, QTD_PRODUZIDA, CUSTO_UNITARIO, CUSTO_TOTAL)
VALUES (1, 1, 2, 6, 5, 30);